[package]
name = "zemeroth"
version = "0.4.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A 2D turn-based hexagonal tactical game."

[workspace]
members = ["zcomponents", "ggwp-zgui", "ggwp-zscene"]

[dependencies]
# ggez = "0.5.0-rc.0" # TODO: get back to crates.io version
ggez = { git = "https://github.com/ozkriff/ggez", rev = "a23153a18" }
ron = "0.4"
rand = "0.6"
log = "0.4"
structopt = "0.2"
env_logger = "0.6"
serde = { version = "1.0", features = ['derive'] }
num = { version = "0.2", default-features = false }
ui = { path = "ggwp-zgui", package = "ggwp-zgui" }
scene = { path = "ggwp-zscene", package = "ggwp-zscene" }
zcomponents = { path = "zcomponents" }
