[package]
name = "zemeroth"
version = "0.4.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A 2D turn-based hexagonal tactical game."

[workspace]
members = ["zcomponents", "ggwp-zgui", "ggwp-zscene"]

[dependencies]
ron = "0.4"
log = "0.4"
env_logger = "0.6"
serde = { version = "1.0", features = ['derive'] }
num = { version = "0.2", default-features = false }
ui = { path = "ggwp-zgui", package = "ggwp-zgui" }
scene = { path = "ggwp-zscene", package = "ggwp-zscene" }
zcomponents = { path = "zcomponents" }

[target.wasm32-unknown-unknown.dependencies]
good-web-game = { git = "https://github.com/not-fl3/good-web-game", features = ["nalgebra"] }
rand = { version = "0.6", features = ["stdweb"] }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ggez = { version="0.5.0-rc.1" }
structopt = "0.2.14"
rand = { version = "0.6" }
