[package]
name = "ggwp-zgui"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Tiny and opionated GUI library"
keywords = ["ggez", "gamedev", "gui"]

[dependencies]
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
good-web-game = { git = "https://github.com/not-fl3/good-web-game", features = ["nalgebra"] }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ggez = { version="0.5.0-rc.1" }
