[package]
name = "ggwp-zscene"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Scene and Actions for GGEZ"
keywords = ["ggez", "gamedev", "2D"]

[dependencies]
ggez = "0.5.0-rc.0"
